apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
type: kubernetes.io/service-account-token