{
 "title": "Flink - Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Flink Cluster", "query": { "query": "label_values(cluster_name)" } },
   { "name": "job_name", "label": "Job Name", "query": { "query": "label_values(job_name)" } },
   { "name": "task_id", "label": "Task Manager", "query": { "query": "label_values(task_manager_id)" } },
   {
    "name": "title",
    "label": "Title",
    "query": {
     "query": "{job_name=\"$title\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Job: $job_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job_name" },
  {
   "title": "Kafka Records",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_pendingRecords{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"}",
     "legendFormat": "Pending: {{tm_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"}",
     "legendFormat": "Consumed: {{tm_id}}"
    }
   ]
  },
  {
   "title": "Kafka Records",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_pendingRecords{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"})",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Kafka Bytes Rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"}",
     "legendFormat": "Consumed {{job_name}}-{{tm_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_incoming_byte_rate{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"}",
     "legendFormat": "Incoming {{job_name}}-{{tm_id}}"
    }
   ]
  },
  {
   "title": "Kafka Bytes Rates",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_incoming_byte_rate{job_name=~\"$job_name\"})",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{job_name=~\"$job_name\"})",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Kafka Poll Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_time_between_poll_avg{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"}",
     "legendFormat": "Poll avg: {{tm_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_time_between_poll_max{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"}",
     "legendFormat": "Poll Max: {{tm_id}}"
    }
   ]
  },
  {
   "title": "Kafka Poll Time",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_time_between_poll_avg{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"})",
     "legendFormat": "Poll average"
    },
    {
     "expr": "max(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_time_between_poll_max{job_name=~\"$job_name\", cluster_name=~\"$cluster_name\", task_manager_id=~\"$task_id\"})",
     "legendFormat": "Poll Max"
    }
   ]
  }
 ]
}